# Generated by Django 3.1.3 on 2020-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, choices=[('a', models.TextField(blank=True, null=True)), ('b', models.TextField(blank=True, null=True)), ('c', models.TextField(blank=True, null=True)), ('d', models.TextField(blank=True, null=True))], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
