# Generated by Django 3.1.3 on 2020-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0002_auto_20201120_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, choices=[('a', models.TextField(blank=True, null=True)), ('b', models.TextField(blank=True, null=True)), ('c', models.TextField(blank=True, null=True)), ('d', models.TextField(blank=True, null=True))], max_length=2, null=True),
        ),
    ]
