# Generated by Django 3.1.3 on 2020-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0003_auto_20201120_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
