# Generated by Django 3.1.3 on 2020-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0004_questions_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
