# Generated by Django 3.1.3 on 2020-11-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0005_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qstnsubject',
            name='totQuestions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='ku_entrance_api.userprofile'),
            preserve_default=False,
        ),
    ]
