# Generated by Django 3.1.3 on 2020-11-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0006_auto_20201121_0508'),
    ]

    operations = []
