# Generated by Django 3.1.3 on 2020-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0007_auto_20201121_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='subject',
        ),
    ]
