# Generated by Django 3.1.3 on 2020-11-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ku_entrance_api', '0008_remove_questions_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ku_entrance_api.qstnsubject'),
            preserve_default=False,
        ),
    ]
